theme: jekyll-theme-minimal
title: Beers Analysis
description: Website for ADA P3 milestone datastory
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Project Documentation
    url: /README.md
